Update Travis CI to use standard test script.
libp2p/go-msgio pull request #2
Opened 2017-11-17 21:45 UTC by kevina

Also remove old go versions from .travis.yml.

2017-11-17 21:49 UTC, Stebalien requested changes

2017-11-17 21:49 UTC, Stebalien commented on .travis.yml
>    - release
I'd explicitly set 1.9.x (yes, we'll need to update it but it forces us to re-run CI when doing so).

2017-11-17 22:04 UTC, Stebalien approved these changes

2017-11-18 07:25 UTC, kevina commented
Note, Travis CI is not enabled for this repo...

2017-12-04 23:56 UTC, kevina commented
@Stebalien let's not merge this one just yet.  I think it might need a rebase.  I will look into it later today.

2017-12-05 00:23 UTC, kevina commented
@Stebalien okay we are green now

2017-12-05 00:34 UTC, merged